apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: wanderlust
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: ritiksuteri/wanderlust-backend:v9
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://ritiksuteri:hzAK7tKFgU9AY8xi@cluster0.rnugh5w.mongodb.net/wandurlust"
