apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: wanderlust
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: ritiksuteri/wanderlust-frontend:v13
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_PATH
              value: "http://localhost:5000"
